apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-deployment
  labels:
    app: borrow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow
  template:
    metadata:
      labels:
        app: borrow
    spec:
      containers:
        - name: borrow-ms
          image: toscanos/borrow:1.0-SNAPSHOT
          ports:
          - containerPort: 8103
          volumeMounts:
          - mountPath: /app/config
            readOnly: true
            name: borrow-conf
      volumes:
      - name: borrow-conf
        configMap:
          name: borrow-conf
          items:
            - key: application.properties
              path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: borrow-service
  labels:
    app: borrow
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32103
      port: 8103
      targetPort: 8103
  selector:
    app: borrow
---
apiVersion: v1
kind: ConfigMap
data:
  application.properties: |-
    #Local MongoDB config
    spring.data.mongodb.authentication-database=admin
    spring.data.mongodb.username=root
    spring.data.mongodb.password=root
    spring.data.mongodb.database=borrow_db
    spring.data.mongodb.port=27017
    spring.data.mongodb.host=borrow-mongodb
    # App config
    server.port=8103
    spring.application.name=BorrowMicroservice
    server.servlet.context-path=/borrow-service
    # Log config
    logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
    # Management config
    management.endpoint.info.enabled=true
    management.security.enabled=false
metadata:
  name: borrow-conf
  namespace: default