version: "3.7"
services:
  
  # Microservizio e porta 

  # Book 8122 
  # Customer 8104 
  # Notification 8105
  # Borrow 8103
  
  ################################# http://localhost:8122/book-service/v2/book

  book-ms: 
    build:
      context: ./book
    container_name: book-ms
    ports:
      - "8122:8122"
    depends_on:
      - mongodb_db

  ################################# http://localhost:8103/borrow-service/v2/borrow

  borrow-ms:
    build:
      context: ./borrow
    container_name: borrow-ms
    ports:
      - "8103:8103"
    depends_on:
      - mongodb_db

  ################################# http://localhost:8104/customer-service/v2/customer

  customer-ms:
    build:
      context: ./customer
    container_name: customer-ms
    ports:
      - "8104:8104"
    depends_on:
      - mongodb_db

 ################################# 

  mongodb_db:
    image: mongo:latest
    container_name: mysolution-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  ################################# http://localhost:8105/notification-service/v2/notification
  
  notification-ms:
    build:
      context: ./notification
    container_name: notification-ms
    ports:
      - "8105:8105"
    depends_on:
      - kafka

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: bitnami/kafka
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"

  


volumes:
 mongodb_data: {}
 postgres_data: {}